### ISSUE TITLE
Menu is not updated

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx-template#21]
We updated a Header menu for JavaScript API and Angular sample browser. It looks like Ignite UI for JavaScript help pulls an updated menu, but Ignite UI for Angular sample does not pick up updated menu.

https://jp.infragistics.com/products/ignite-ui-angular/angular/components/grid.html (header menu items are different from Ignite UI for JavaScript API doc (https://jp.igniteui.com/help/api/2018.1/)
Also @jasonzajac noticed there's cross site origin access error on the site.

![image](https://user-images.githubusercontent.com/6439482/42945013-e8103ce0-8b6f-11e8-8b0c-0ac3cd1d108a.png)

From @DaizenIG

**Comment by jasonzajac** [comment]
@tiliev I found a couple other things related to the issue @DaizenIG presented. I noticed that in multiple environments (local, dev and staging) the navigation and footer do not update from the AJAX request. It seems the only environment that works is EN on production.

Looking at this further, I see two things:
1. There's a data attribute called "data-nav-base-url" that has a hard-coded link to EN production (www.infragistics.com) that's used in the script to make the AJAX call. I think that's causing a cross-domain origin issue.
2. This item I wasn't sure on, because I don't know what else relies on the template, but if it's just Indigo and Angular, we can probably switch the page where we're getting the content from. So instead of pulling from "/navigation-ignite", we can just do "/ignite".

We probably need to make some updates to the fallback HTML as well. Let me know if you need me to help out with this.

**Comment by tiliev** [comment]
@jasonzajac,
1. Yes, you are right, I'm updating it to be environment-specific.
2. It turns out we should use https://www.infragistics.com/navigation instead of https://www.infragistics.com/navigation-ignite.
