### ISSUE TITLE
Lazy loading is not working properly with samples theming

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx-template#273]
1. Open [column moving](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column-moving) sample.
2. Change to some of the Dark themes
3. Scroll down to the next sample (that will be lazy loaded)
4. Theming is not applied.

**Comment by dobromirts** [comment]
This problem is not reproducing on a local environment and it persists on staging and production, the reason for this behavior might be the current way the code view is rendering on the page.

As we are currently changing the whole code view markup and its rendering process, let us see if this problem will be reproducible after this update.

**Comment by zdrawku** [comment]
This issue will be on production/master after the 12.0.0 release
