### ISSUE TITLE
Template inserts broken links to marketing images/banners

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-docfx-template#283]
docfx-template inserts broken links to marketing images/banners, e.g.

https://staging.infragistics.com/blazorsite/components/charts/chart-overview.html#blazor-treemap

![image](https://user-images.githubusercontent.com/11665978/112162311-528fbc80-8bc2-11eb-9c0d-47dee39fd170.png)

@zdrawku 
I think that the root cause of this issue is that the template assumes that all topics are on the same level but in xplat docs topics are on different levels, e.g.

/vnext/doc/en/components/bullet-graph.md
/vnext/doc/en/components/**charts**/chart-overview.md
/vnext/doc/en/components/**charts/types**/area-chart.md

so the template needs to generate the path to images based on a location of current topic

**Comment by HristoP96** [comment]
@HUSSAR-mtrela Hi Martin, this issue is no more reproducible - 
![image](https://user-images.githubusercontent.com/25771040/113290750-be78d000-92fa-11eb-934c-8e60ebc360c7.png)

[https://staging.infragistics.com/blazorsite/components/charts/chart-overview.html#but-wait-theres-more](https://staging.infragistics.com/blazorsite/components/charts/chart-overview.html#but-wait-theres-more)

Let us know if the issue still exists on your side :)
