### ISSUE TITLE
Razor and CS Code Snippets have wrong language tag

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-docfx-template#435]
[Razor and CS code snippet](https://github.com/IgniteUI/igniteui-xplat-docs/blob/vnext/doc/en/components/grids/tree-grid/overview.md?plain=1#L36) are displayed as HTML snippets instead of CS/RAZOR snippets:
https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/tree-grid/overview#dependencies

![image](https://user-images.githubusercontent.com/11665978/230646321-934d42b1-8be5-46f7-b0a9-d8e60dec5434.png)

**Comment by dobromirts** [comment]
This issue is caused by the logic specified in the xplat repo MarkdownTransformer:
![override-codeblock-lang](https://github.com/IgniteUI/igniteui-docfx-template/assets/46093564/0162cb81-e473-4b64-90bb-1bc810103a85)

When it is removed and the latest version of the template is used the result is:

![local-result](https://github.com/IgniteUI/igniteui-docfx-template/assets/46093564/a278d389-c61e-4ba2-91a3-4f2b4bdc45d9)

**Comment by zdrawku** [comment]
@dobromirts the PR with docfx version upgrade is now merged, whats the next step from our side?

**Comment by dobromirts** [comment]
> @dobromirts the PR with docfx version upgrade is now merged, whats the next step from our side?

This pr: https://github.com/IgniteUI/igniteui-xplat-docs/pull/851 is removing the razor language replacement for the xplat documentation.

**Comment by HUSSAR-mtrela** [comment]
this issue is fixed now on staging
https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/tree-grid/overview#dependencies
